### PR TITLE
Fix #23: Build with target of Java 6

### LINKED ISSUE #23: Indicate required Java version is 8
I tried running this with 7 and got an esoteric error message. Installing jdk8 helped, after I updated/fixed my path and deleted some old executables (java.exe javaw.exe javaws.exe) from my windows\system32 directory. That's all a lot of work for a non-technical person to get this up and running.

Here are some stackoverflow's that helped me:
http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0
http://stackoverflow.com/questions/15277496/registry-key-has-value-1-7-but-1-6-is-required-java-1-7-is-installed

### PR DESCRIPTION
**Pull request by panathea**
Specify build target to run on machines with Java 6+ (better for stable distros like Ubuntu/Debian).

If you pull in my other PRs, we'll need to rebuild after all the changes are in.

### CODE REVIEW

**Comment by brentn** [comment]
I have indeed merged your other fixes.  
Would you mind making a new .jar for this one?  (I do it rarely enough that I need to look it up each time :)

**Comment by morinted** [comment]
Sure, I'll make a jar tonight.

**Comment by morinted** [comment]
Rebuilt with all the changes! I'd probably recommend running it to make sure it works on your system (I'm on a Mac here, but I don't see why it wouldn't work on PC; it's Java!)

**Comment by brentn** [comment]
(I don't have a PC either - I'm a Linux guy)
But it work well for me :)

**Pull request merged**
